package com.mazhen.hibernate;

// Generated 2014-10-29 15:17:04 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Myuser generated by hbm2java
 */
@Entity
@Table(name = "MYUSER")
public class Myuser implements java.io.Serializable {

	private BigDecimal id;
	private String username;
	private String password;

	public Myuser() {
	}

	public Myuser(BigDecimal id, String username, String password) {
		this.id = id;
		this.username = username;
		this.password = password;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "USERNAME", nullable = false, length = 20)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", nullable = false, length = 30)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
